apply plugin: 'com.android.application'

android {
    namespace 'com.genymobile.scrcpy'
    compileSdk 35
    applicationVariants.configureEach { variant ->
        variant.outputs.configureEach { output ->
            def versionName = variant.versionName
            outputFileName = "off-screen-${versionName}"
        }
    }
    defaultConfig {
        applicationId "com.genymobile.scrcpy"
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 30301
        versionName "3.3.1"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}

apply from: "$project.rootDir/config/android-checkstyle.gradle"
